# Require Environment Variables
# - BLOB_CONTAINER_URL 
# - STORAGE_KEY
language: ruby
rvm:
  - 2.5
sudo: required
notifications:
  email: false
before_script:
  - chmod +x ./.travis/cibuild
  - chmod +x ./.travis/deploy-to-azure.sh
script: ./.travis/cibuild
after_success:
  - # deploy to blob storage
  - ./.travis/deploy-to-azure.sh
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer