# Site settings
title:          trans feed
description:    "Translated Feed from en-us to ja-jp"
baseurl:        "https://trans-feed.azurewebsites.net"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         kheiakiyama
  url:          https://cv.kheiakiyama.com
  email:        kheiakiyama@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
