# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: KeyVaultVariableGroup
  - name: rubyVersion
    value: '2.5.5' #available versions 2.4.6,2.5.5,2.6.3
  - name: BlobTranslatedPostsUrl
    value: 'https://transfeedclouddemo.blob.core.windows.net/translated'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Jekyll build contents' 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo apt-get install -y git gcc build-essential libreadline-dev zlib1g-dev
      displayName: 'Install dependencies of installing ruby'
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '= $(rubyVersion)'
        addToPath: true
      displayName: 'Install ruby'
    - script: |
        ruby --version
        gem install bundler
        bundle -v
      displayName: 'Install bundler'
    - script: |
        wget https://aka.ms/downloadazcopy-v10-linux
        tar -xvf downloadazcopy-v10-linux
        sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
        azcopy --version
      displayName: 'Install azcopy'
    - script: |
        mkdir $(Agent.TempDirectory)/_tmp
        azcopy copy "$(BlobPathWithSas)" "$(Agent.TempDirectory)/_tmp/" --recursive=true
        rsync -avr $(Agent.TempDirectory)/_tmp/ ./_posts
        ls -la ./_posts
      displayName: 'Copy current posts to local'
    - script: |
        bundle install
      displayName: 'Bundle Install'
    - script: |
        chmod +x $(Build.Repository.LocalPath)/.travis/cibuild
        $(Build.Repository.LocalPath)/.travis/cibuild
      displayName: 'Run jekyll build'
