# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  rubyVersion: '2.5.7'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Jekyll build contents' 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo apt-get install git
        git --version
      displayName: 'Install git'
    - script: |
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        cd ~/.rbenv && src/configure && make -C src
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        ~/.rbenv/bin/rbenv init
        cat ~/.bashrc
        source ~/.bashrc
        git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
        rbenv install $(rubyVersion)
        rbenv global $(rubyVersion)
      displayName: 'Install ruby'
    - script: |
        sudo gem install bundler
        bundle -v
      displayName: 'Install bundler'
    - script: |
        wget https://aka.ms/downloadazcopy-v10-linux
        tar -xvf downloadazcopy-v10-linux
        sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
        azcopy --version
      displayName: 'Install azcopy'
    - script: |
        bundle install
      displayName: 'Bundle Install'
    - script: |
        chmod +x $(Build.Repository.LocalPath)/.travis/cibuild
        $(Build.Repository.LocalPath)/.travis/cibuild
      displayName: 'Run jekyll build'
