name: "Azure CDN and Blob static website CD"
on: # rebuild master branch changes
  push:
    branches:
      - master
  repository_dispatch:
    types: [action_trigger]

env:
  STORAGE_NAME: 'transfeedclouddemo'
  TRANSLATED_CONTAINER_NAME: 'translated'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Set up bundler
      run: gem install bundler
    - uses: kheiakiyama/install-azcopy-action@v1.0.1
      with: 
        version: 'v10'
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Copy current posts to local'
      run: |
        mkdir ./_tmp
        echo "https://$STORAGE_NAME.blob.core.windows.net/$TRANSLATED_CONTAINER_NAME"
        azcopy_v10 copy "https://$STORAGE_NAME.blob.core.windows.net/$TRANSLATED_CONTAINER_NAME" ./_tmp/ --recursive=true || true
        rsync -avr ./_tmp/ ./_posts
        ls -la ./_posts
    - name: nokogiri dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml2 libxslt1-dev
    - name: jekyll build
      run: |
        bundle install --jobs 4
        bundle exec jekyll build
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: false
    - name: Upload jekyll output
      uses: actions/upload-artifact@v1
      with:
        name: jekyll
        path: './_site'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: kheiakiyama/install-azcopy-action@v1.0.1
      with: 
        version: 'v10'
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Download jekyll output
      uses: actions/download-artifact@v1
      with:
        name: jekyll
    - name: azcopy upload jekyll content
      run: |
        azcopy_v10 --version | grep 'azcopy'
        echo "https://$STORAGE_NAME.blob.core.windows.net/\$web"
        azcopy_v10 sync ./jekyll "https://$STORAGE_NAME.blob.core.windows.net/\$web" --recursive=true --delete-destination=true
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge -g trans-feed --profile-name trans-feed -n trans-feed --content-paths '/*'
